server:
  port: 3010

spring:
  profiles:
    active: dev


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  #    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  mapper-locations:
    - classpath:mapper/**/*.xml
  global-config:
    db-config:
      table-underline: false
#publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIG8/mcfSHs8onQPl7pJsTQZbTZik2haO5D618+hJKnM+DTWv7XpqxpARo7syByiwXv0pTAHWE48Bgyi5DeWu3ECAwEAAQ==
logging:
  config: classpath:log4j2-spring.xml