server:
  port: 4000
spring:
  application:
    name: xy-club-oss
minio:
  url: http://116.198.217.150:9000
  accessKey: minioadmin
  secretKey: minioadmin


#nacos:
#  config:
#    secret-key: nacos
#    access-key: nacos
#    server-addr: http://116.198.217.150:8848/
#    data-id: xy-club-oss
#    group: DEFAULT_GROUP
#    type: yaml
#    auto-refresh: true
##    enable-remote-sync-config: true
#    remote-first: true
#    bootstrap:
#      enable: true
