name: Maven Build and Docker Image CI

on:
  push:
    branches: [ "docker-images-*" ]
  pull_request:
    branches: [ "docker-images-*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_VERSION: 4.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Dependies Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |
          mvn clean package -Dmaven.test.skip=true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to DockerAlibaba
        run: |
          docker login --username=${{ secrets.ALIYUN_REGISTRY_USER }} --password=${{ secrets.ALIYUN_REGISTRY_PASSWORD }} registry.cn-hangzhou.aliyuncs.com

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./big-market-app
          file: ./big-market-app/Dockerfile
          # 所需要的体系结构，可以在 Available platforms 步骤中获取所有的可用架构 https://docs.docker.com/build/building/multi-platform/
          platforms: linux/amd64
          # 镜像推送时间
          push: ${{ github.event_name != 'pull_request' }}
          # 给清单打上多个标签
          tags: |
            fuzhengwei/big-market-app:${{ env.IMAGE_VERSION }}
            fuzhengwei/big-market-app:latest    

      - name: Tag image for Alibaba Cloud
        run: |
          docker tag fuzhengwei/big-market-app:${{ env.IMAGE_VERSION }} registry.cn-hangzhou.aliyuncs.com/fuzhengwei/big-market-app:${{ env.IMAGE_VERSION }}
          docker tag fuzhengwei/big-market-app:latest registry.cn-hangzhou.aliyuncs.com/fuzhengwei/big-market-app:latest

      - name: Push to Alibaba Cloud Container Registry
        run: |
          docker push registry.cn-hangzhou.aliyuncs.com/fuzhengwei/big-market-app:${{ env.IMAGE_VERSION }}
          docker push registry.cn-hangzhou.aliyuncs.com/fuzhengwei/big-market-app:latest
